
export const bookData=[
    { bookid:4560, title: 'Harry Potter', author: 'J. K. Rowling', price:'Rs. 600',desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"},
    { bookid:3560, title: 'The Matrix', author: 'Neo Trinity', price:'Rs. 200',desc:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."},
    { bookid:5565, title: 'Lord of the Rings', author: 'Gandalf Grey', price:'Rs. 700',desc:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text."},
    { bookid:3865, title: 'Alchemist', author: 'Paulo', price:'Rs. 900',desc:"The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham."},
    { bookid:5656, title: 'Harry Potter 2', author: 'J. K. Rowling', price:'Rs. 800',desc:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source."},
    // { bookid:8256, title: 'Matrix', author: 'Neo', price:'Rs. 200',desc:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source."},
    // { bookid:6326, title: 'Lord of the Rings', author: 'Gandalf Grey', price:'Rs. 700',desc:'7lfajdlfjsla dlajflkjfd'},
    // { bookid:2169, title: 'Alchemist', author: 'Paulo', price:'Rs. 900',desc:'8lfajdlfjsla dlajflkjfd'}
]